### ISSUE TITLE
Configure Disposal for a not NaluShell

### ISSUE THREAD

**Issue by georg1592** [nalu-development/nalu#14]
### Describe the bug

Using the Extension Method "ConfigureForPageDisposal" for a **not** NaluShell always throws the Exception "Nalu navigation already handles page disposal."
I think the Exception should be thrown if the user tries to call this Method **on** a NaluShell Object.
The condition is the wrong way around.

### Steps to reproduce

- call the ConfigureForPageDisposal Extension Method on a used Shell Object in a .net Maui Application
- Start the Program -> Exception is thrown

### Expected behaviour

No Exception is thrown since it is not a NaluShell Object.

**Comment by albyrock87** [comment]
@georg1592 thanks for catching this error: this should be fixed in 1.2.1 (available in a few minutes).
Please note that `ShellContent`s won't be disposed due to the way `Shell` works.

**Comment by albyrock87** [comment]
@georg1592 version 1.3.0 now contains a new flag to provide automatic dispose `ShellContent`s too.
See more here: https://nalu-development.github.io/nalu/#call-dispose-on-page-and-viewmodel-when-the-page-is-popped

**Comment by albyrock87** [comment]
@georg1592 version 2.0.0 will be soon released and I had to remove the disposal of `ShellContents` because there are some use cases where it shouldn't be disposed (i.e. tabs) unless the user leaves the `ShellSection`.
Given that it's not obvious what the consumer desires, I choose to remove the flag I added in 1.3.0.

On the other hand, I've improved the `Nalu` navigation abstraction to take into consideration a lot of special use cases, and also to support people who don't want to use MVVM pattern.
